apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transit-ingress
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: transit.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: transit-backend-service
                port:
                  number: 80